Add option for AGENT-only configuration

diff --git a/scripts/configure b/scripts/configure
--- a/scripts/configure
+++ b/scripts/configure
@@ -56,6 +56,20 @@ else
 fi | tee /etc/consul.d/50-datacenter.json
 
 systemctl daemon-reload
-test "${ENABLE:-true}" = false || systemctl enable consul
-test "${START:-true}" = false || systemctl start consul
-test "${RESTART:-true}" = false || systemctl restart consul
+
+if test "${AGENT:-false}" != false; then
+    if test -z "${SERVER:-''}"; then
+        echo 'Failed: SERVER is missing or empty' >&2
+        exit 1
+    fi
+
+    printf '{ "retry_join": ["%s"] }' "${SERVER}" | tee /etc/consul.d/20-bootstrap.json
+
+    test "${ENABLE:-true}" = false || systemctl enable consul-agent
+    test "${START:-true}" = false || systemctl start consul-agent
+    test "${RESTART:-true}" = false || systemctl restart consul-agent
+else
+    test "${ENABLE:-true}" = false || systemctl enable consul
+    test "${START:-true}" = false || systemctl start consul
+    test "${RESTART:-true}" = false || systemctl restart consul
+fi
